name: Terraform Azure Deployment (Windows VM)

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify admin password secret
        run: |
          if [ -z "${{ secrets.VM_ADMIN_PASSWORD }}" ]; then
            echo "ERROR: Secret VM_ADMIN_PASSWORD is empty or missing." >&2
            exit 1
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -no-color

      - name: Terraform Plan
        working-directory: ./terraform
        env:
          TF_VAR_admin_password: ${{ secrets.VM_ADMIN_PASSWORD }}
        run: |
          terraform plan -no-color \
            -var-file="terraform.tfvars"

      - name: Terraform Apply (main only)
        if: github.ref == 'refs/heads/main'
        working-directory: ./terraform
        env:
          TF_VAR_admin_password: ${{ secrets.VM_ADMIN_PASSWORD }}
        run: |
          terraform apply -auto-approve -no-color \
            -var-file="terraform.tfvars"
